"""Auth subsystem: credentials, stores, and resolution."""

from .context import AuthContext, default_provider_auth_context
from .credential_store import InMemoryCredentialStore, JsonFileCredentialStore
from .resolve import AuthResolutionOverrides, resolve_provider_auth
from .types import (
    ApiKeyAuth,
    ApiKeyCredential,
    ApiKeyResolveInput,
    AuthCheck,
    AuthEvent,
    AuthEventAuthUrl,
    AuthEventDeviceCode,
    AuthEventInfo,
    AuthEventProgress,
    AuthInfoLink,
    AuthInteraction,
    AuthOperationOptions,
    AuthPrompt,
    AuthPromptManualCode,
    AuthPromptSecret,
    AuthPromptSelect,
    AuthPromptText,
    AuthResult,
    AuthSelectOption,
    AuthType,
    Credential,
    CredentialInfo,
    CredentialStore,
    ModelAuth,
    OAuthAuth,
    OAuthCredential,
    ProviderAuth,
)

__all__ = [
    "AuthContext",
    "default_provider_auth_context",
    "InMemoryCredentialStore",
    "JsonFileCredentialStore",
    "AuthResolutionOverrides",
    "resolve_provider_auth",
    "ApiKeyAuth",
    "ApiKeyCredential",
    "ApiKeyResolveInput",
    "AuthCheck",
    "AuthEvent",
    "AuthEventAuthUrl",
    "AuthEventDeviceCode",
    "AuthEventInfo",
    "AuthEventProgress",
    "AuthInfoLink",
    "AuthInteraction",
    "AuthOperationOptions",
    "AuthPrompt",
    "AuthPromptManualCode",
    "AuthPromptSecret",
    "AuthPromptSelect",
    "AuthPromptText",
    "AuthResult",
    "AuthSelectOption",
    "AuthType",
    "Credential",
    "CredentialInfo",
    "CredentialStore",
    "ModelAuth",
    "OAuthAuth",
    "OAuthCredential",
    "ProviderAuth",
]
