"""karen-agent: agent loop on top of karen-ai.

Python port of `@earendil-works/pi`'s `packages/agent` (core loop layer; the
coding-agent app, MCP, and TUI stay out of scope for now). The loop works with
AgentMessage throughout and transforms to Message[] only at the LLM call boundary.
"""

from .agent_loop import agent_loop, agent_loop_continue, run_agent_loop, run_agent_loop_continue
from .stream_fn import get_default_stream_fn, models_stream_fn, set_default_stream_fn
from .tools import (
    BashExecution,
    Edit,
    ExecutionError,
    ImageProcessingFailed,
    ProcessedImage,
    create_bash_tool,
    create_builtin_tools,
    create_edit_tool,
    create_read_tool,
    create_write_tool,
)
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentEventSink,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentMessage,
    AgentRequestUpdate,
    AgentStartEvent,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    AgentToolUpdateCallback,
    AgentTurnContext,
    AgentTurnDecision,
    BeforeToolCallContext,
    BeforeToolCallResult,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    PrepareNextTurnContext,
    PrepareRequestContext,
    QueueMode,
    StreamFn,
    ToolExecutionEndEvent,
    ToolExecutionMode,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)

__all__ = [
    "agent_loop",
    "agent_loop_continue",
    "run_agent_loop",
    "run_agent_loop_continue",
    "get_default_stream_fn",
    "models_stream_fn",
    "set_default_stream_fn",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentEventSink",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentRequestUpdate",
    "AgentStartEvent",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "AgentTurnContext",
    "AgentTurnDecision",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "PrepareNextTurnContext",
    "PrepareRequestContext",
    "QueueMode",
    "StreamFn",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "BashExecution",
    "Edit",
    "ExecutionError",
    "ImageProcessingFailed",
    "ProcessedImage",
    "create_bash_tool",
    "create_builtin_tools",
    "create_edit_tool",
    "create_read_tool",
    "create_write_tool",
]
