"""karen-agent: agent loop on top of karen-ai.

Python port of `@earendil-works/pi`'s `packages/agent` (core loop layer; the
coding-agent app, MCP, and TUI stay out of scope for now). The loop works with
AgentMessage throughout and transforms to Message[] only at the LLM call boundary.
"""

from .agent import DEFAULT_MODEL, Agent, AgentInitialState, AgentState, default_convert_to_llm
from .agent_loop import agent_loop, agent_loop_continue, run_agent_loop, run_agent_loop_continue
from .config import (
    DEFAULT_MAX_AGENT_RETRY_DELAY_MS,
    DEFAULT_RETRY_POLICY,
    RetryPolicy,
    validate_compaction_settings,
    validate_retry_policy,
    validate_tool_names,
)
from .env import (
    ExecutionEnv,
    FileError,
    FileErrorCode,
    FileInfo,
    FileKind,
    FileSystem,
    LocalExecutionEnv,
    Shell,
    ShellExecOptions,
    ShellExecResult,
    ShellOutputCaptureOptions,
    ShellOutputLimits,
    ShellOutputMetadata,
    ShellOutputRetention,
    TextLine,
    TextLineReader,
)
from .hooks import (
    HOOK_NAMES,
    AfterResponseEvent,
    AfterResponseResult,
    AfterToolEvent,
    AfterToolResult,
    BeforeCompactionEvent,
    BeforeCompactionResult,
    BeforeDriveEvent,
    BeforeNavigationEvent,
    BeforeNavigationResult,
    BeforePayloadEvent,
    BeforePayloadResult,
    BeforeRequestEvent,
    BeforeRequestResult,
    BeforeRunEndEvent,
    BeforeRunEndResult,
    BeforeRunEvent,
    BeforeRunResult,
    BeforeToolEvent,
    BeforeToolResult,
    HarnessStreamOptions,
    HookRegistry,
    StreamOptionsPatch,
    ToolBlock,
    TransformContextEvent,
    TransformContextResult,
    apply_stream_options_patch,
    create_stream_options_patch,
)
from .messages import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    BashExecutionMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    CustomMessage,
    bash_execution_to_text,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
    create_custom_message,
)
from .prompt_templates import (
    LoadPromptTemplatesResult,
    PromptTemplateDiagnostic,
    SourcedPath,
    SourcedPromptTemplate,
    format_prompt_template_invocation,
    load_prompt_templates,
    load_sourced_prompt_templates,
    parse_command_args,
    substitute_args,
)
from .proxy import ProxyStreamOptions, build_proxy_request_options, process_proxy_event, stream_proxy
from .resources import PromptTemplate, Resources, Skill
from .result import (
    BranchSummaryError,
    CompactionError,
    Err,
    Ok,
    Result,
    err,
    get_or_throw,
    get_or_undefined,
    ok,
    to_error,
)
from .search import EntrySearchHit, SearchQuery, SessionSearchHit, SessionSearchService
from .skills import (
    IGNORE_FILE_NAMES,
    MAX_DESCRIPTION_LENGTH,
    MAX_NAME_LENGTH,
    LoadSkillsResult,
    LoadSourcedSkillsResult,
    SourcedSkill,
    SourcedSkillDiagnostic,
    SkillDiagnostic,
    SkillDiagnosticCode,
    format_skill_invocation,
    load_skills,
    load_sourced_skills,
)
from .stream_fn import get_default_stream_fn, models_stream_fn, set_default_stream_fn
from .system_prompt import escape_xml, format_skills_for_system_prompt
from .tools import (
    BashExecution,
    Edit,
    ExecutionError,
    ImageProcessingFailed,
    ProcessedImage,
    create_bash_tool,
    create_builtin_tools,
    create_edit_tool,
    create_read_tool,
    create_write_tool,
)
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentEventSink,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentMessage,
    AgentRequestUpdate,
    AgentStartEvent,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    AgentToolUpdateCallback,
    AgentTurnContext,
    AgentTurnDecision,
    BeforeToolCallContext,
    BeforeToolCallResult,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    PrepareNextTurnContext,
    PrepareRequestContext,
    QueueMode,
    StreamFn,
    ToolExecutionEndEvent,
    ToolExecutionMode,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from .utils.shell_output import (
    ShellCaptureOptions,
    ShellCaptureProgress,
    ShellCaptureResult,
    execute_shell_with_capture,
)

__all__ = [
    "agent_loop",
    "agent_loop_continue",
    "run_agent_loop",
    "run_agent_loop_continue",
    "get_default_stream_fn",
    "models_stream_fn",
    "set_default_stream_fn",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentEventSink",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentRequestUpdate",
    "AgentStartEvent",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "AgentTurnContext",
    "AgentTurnDecision",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "PrepareNextTurnContext",
    "PrepareRequestContext",
    "QueueMode",
    "StreamFn",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "BashExecution",
    "Edit",
    "ExecutionError",
    "ImageProcessingFailed",
    "ProcessedImage",
    "create_bash_tool",
    "create_builtin_tools",
    "create_edit_tool",
    "create_read_tool",
    "create_write_tool",
    # result (M3)
    "Result",
    "Ok",
    "Err",
    "ok",
    "err",
    "get_or_throw",
    "get_or_undefined",
    "to_error",
    "CompactionError",
    "BranchSummaryError",
    # messages (M3)
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "BashExecutionMessage",
    "CustomMessage",
    "BranchSummaryMessage",
    "CompactionSummaryMessage",
    "bash_execution_to_text",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_custom_message",
    "convert_to_llm",
    # resources (M3)
    "Skill",
    "PromptTemplate",
    "Resources",
    # hooks (M3)
    "HookRegistry",
    "HOOK_NAMES",
    "HarnessStreamOptions",
    "StreamOptionsPatch",
    "apply_stream_options_patch",
    "create_stream_options_patch",
    "BeforeRunEvent",
    "BeforeRunResult",
    "BeforeDriveEvent",
    "BeforeRunEndEvent",
    "BeforeRunEndResult",
    "TransformContextEvent",
    "TransformContextResult",
    "BeforeRequestEvent",
    "BeforeRequestResult",
    "BeforePayloadEvent",
    "BeforePayloadResult",
    "AfterResponseEvent",
    "AfterResponseResult",
    "BeforeToolEvent",
    "ToolBlock",
    "BeforeToolResult",
    "AfterToolEvent",
    "AfterToolResult",
    "BeforeCompactionEvent",
    "BeforeCompactionResult",
    "BeforeNavigationEvent",
    "BeforeNavigationResult",
    # prompt templates (M3)
    "load_prompt_templates",
    "load_sourced_prompt_templates",
    "LoadPromptTemplatesResult",
    "PromptTemplateDiagnostic",
    "SourcedPath",
    "SourcedPromptTemplate",
    "parse_command_args",
    "substitute_args",
    "format_prompt_template_invocation",
    # system prompt (M3)
    "format_skills_for_system_prompt",
    "escape_xml",
    # agent (M5)
    "Agent",
    "AgentState",
    "AgentInitialState",
    "default_convert_to_llm",
    "DEFAULT_MODEL",
    # config (M5)
    "RetryPolicy",
    "DEFAULT_RETRY_POLICY",
    "DEFAULT_MAX_AGENT_RETRY_DELAY_MS",
    "validate_tool_names",
    "validate_retry_policy",
    "validate_compaction_settings",
    # skills (M5)
    "load_skills",
    "load_sourced_skills",
    "LoadSkillsResult",
    "LoadSourcedSkillsResult",
    "SourcedSkill",
    "SourcedSkillDiagnostic",
    "SkillDiagnostic",
    "SkillDiagnosticCode",
    "format_skill_invocation",
    "MAX_NAME_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "IGNORE_FILE_NAMES",
    # execution environment (M6)
    "ExecutionEnv",
    "FileSystem",
    "Shell",
    "LocalExecutionEnv",
    "FileError",
    "FileErrorCode",
    "FileInfo",
    "FileKind",
    "TextLine",
    "TextLineReader",
    "ShellExecOptions",
    "ShellExecResult",
    "ShellOutputCaptureOptions",
    "ShellOutputLimits",
    "ShellOutputMetadata",
    "ShellOutputRetention",
    # shell capture (M6)
    "execute_shell_with_capture",
    "ShellCaptureOptions",
    "ShellCaptureProgress",
    "ShellCaptureResult",
    # search interfaces (M6)
    "SearchQuery",
    "SessionSearchHit",
    "EntrySearchHit",
    "SessionSearchService",
    # proxy stream fn (M6)
    "stream_proxy",
    "ProxyStreamOptions",
    "build_proxy_request_options",
    "process_proxy_event",
]
